dataset:
  train_rgb_dir: /mnt/lyt/matched_data
  train_lidar_dir: /mnt/lyt/matched_data
  val_rgb_dir: /mnt/lyt/matched_data
  val_lidar_dir: /mnt/lyt/matched_data
  image_size: [512, 512] 

model:
  model_id: runwayml/stable-diffusion-v1-5
  lidar_channels: 3
  t_max: 1000
  time_dim: 128
 
train:
  batch_size: 24  # 安全的增加到24，3张卡总batch=72
  max_epochs: 50

lr: 1e-4  
weight_decay: 0.0

log_dir: ./logs